version: 1
services:
  - type: web
    name: ragnar
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ragnar.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ragnar.settings
    autoDeploy: true
    postDeploy:
      - python manage.py makemigrations
      - python manage.py migrate
