# Generated by Django 5.1.1 on 2024-09-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragnar_app', '0002_alter_manager_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AlterField(
            model_name='manager',
            name='cnic',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
