# Generated by Django 5.1.1 on 2024-10-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragnar_app', '0004_user_deleted_at_user_restored_at_user_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
