# Generated by Django 5.1.1 on 2024-10-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragnar_app', '0006_manager_username_user_last_login_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'MANAGER'), ('customer', 'CUSTOMER')], default='customer', max_length=10),
        ),
    ]
