# Generated by Django 5.1.1 on 2024-10-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragnar_app', '0007_delete_manager_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('manager', 'MANAGER'), ('customer', 'CUSTOMER')], max_length=10),
        ),
    ]
