# Generated by Django 5.1.1 on 2024-10-20 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragnar_app', '0009_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
